from pathlib import Path
import re
path = Path('js/scrollytelling.js')
text = path.read_text()

# Update updateInfoCard
pattern_info = re.compile(r"""\s+updateInfoCard\(data\) {\n\s+const iconEl = document.getElementById\('region-icon'\);\n\s+const nameEl = document.getElementById\('region-name'\);\n\s+const statsEl = document.getElementById\('region-stats'\);\n\s+\n\s+// Animate out\n\s+gsap.to\(\[iconEl, nameEl, statsEl\], {\n\s+\s+opacity: 0,\n\s+\s+y: -10,\n\s+\s+duration: 0.3,\n\s+\s+onComplete: \(\) => {\n\s+\s+\s+// Update content\n\s+\s+\s+iconEl.textContent = data.icon;\n\s+\s+\s+nameEl.textContent = data.name;\n\s+\s+\s+statsEl.innerHTML = `\n\s+\s+\s+\s+<span class=\\"stat\\">Population: \$\{data.population\}</span>\n\s+\s+\s+\s+<span class=\\"stat\\">Language: \$\{data.language\}</span>\n\s+\s+\s+`;\n\s+\s+\s+\n\s+\s+\s+// Animate in\n\s+\s+\s+gsap.to\(\[iconEl, nameEl, statsEl\], {\n\s+\s+\s+\s+opacity: 1,\n\s+\s+\s+\s+y: 0,\n\s+\s+\s+\s+duration: 0.5,\n\s+\s+\s+\s+stagger: 0.1\n\s+\s+\s+}\);\n\s+\s+}\n\s+}\);\n\s+}\n""", re.MULTILINE)

replacement_info = """    updateInfoCard(data) {\n        const iconEl = document.getElementById('region-icon');\n        const nameEl = document.getElementById('region-name');\n        const statsEl = document.getElementById('region-stats');\n\n        if (!HAS_GSAP) {\n            iconEl.textContent = data.icon;\n            nameEl.textContent = data.name;\n            statsEl.innerHTML = `\n                <span class="stat">Population: ${data.population}</span>\n                <span class="stat">Language: ${data.language}</span>\n            `;\n            return;\n        }\n\n        // Animate out\n        gsap.to([iconEl, nameEl, statsEl], {\n            opacity: 0,\n            y: -10,\n            duration: 0.3,\n            onComplete: () => {\n                iconEl.textContent = data.icon;\n                nameEl.textContent = data.name;\n                statsEl.innerHTML = `\n                    <span class="stat">Population: ${data.population}</span>\n                    <span class="stat">Language: ${data.language}</span>\n                `;\n\n                gsap.to([iconEl, nameEl, statsEl], {\n                    opacity: 1,\n                    y: 0,\n                    duration: 0.5,\n                    stagger: 0.1\n                });\n            }\n        });\n    }\n"""

text, count = pattern_info.subn(replacement_info, text)
if count != 1:
    raise SystemExit('updateInfoCard pattern not replaced')

pattern_title = re.compile(r"""\s+updateTitleCard\(stepIndex\) {\n\s+const titleEl = document.getElementById\('chart-title'\);\n\s+const subtitleEl = document.getElementById\('chart-subtitle'\);\n\s+\n\s+const titles = \[\n[\s\S]+?\n\s+\];\n\s+\n\s+const data = titles\[stepIndex\] \|\| titles\[0\];\n\s+\n\s+// Animate title change\n\s+gsap.to\(\[titleEl, subtitleEl\], {\n\s+\s+opacity: 0,\n\s+\s+y: -10,\n\s+\s+duration: 0.3,\n\s+\s+onComplete: \(\) => {\n\s+\s+\s+titleEl.textContent = data.title;\n\s+\s+\s+subtitleEl.textContent = data.subtitle;\n\s+\s+\s+\n\s+\s+\s+gsap.to\(\[titleEl, subtitleEl\], {\n\s+\s+\s+\s+opacity: 1,\n\s+\s+\s+\s+y: 0,\n\s+\s+\s+\s+duration: 0.4,\n\s+\s+\s+\s+stagger: 0.1\n\s+\s+\s+}\);\n\s+\s+}\n\s+}\);\n\s+}\n""", re.MULTILINE)

replacement_title = """    updateTitleCard(stepIndex) {\n        const titleEl = document.getElementById('chart-title');\n        const subtitleEl = document.getElementById('chart-subtitle');\n\n        const titles = [\n            { title: 'Ethnic Breakdown', subtitle: 'Iran\'s diverse population' },\n            { title: 'Persians: 61%', subtitle: 'The largest ethnic group' },\n            { title: 'Azeris: 16%', subtitle: 'Northwestern influence' },\n            { title: 'Kurds: 10%', subtitle: 'Mountain communities' },\n            { title: 'Lurs: 6%', subtitle: 'Western tribal heritage' },\n            { title: 'Arabs: 2%', subtitle: 'Southern coastal regions' },\n            { title: 'Baluchis: 2%', subtitle: 'Southeastern frontier' },\n            { title: 'Turkmen & Others: 3%', subtitle: 'Northern steppes & more' },\n            { title: 'Linguistic Diversity', subtitle: 'Many languages, one nation' }\n        ];\n\n        const data = titles[stepIndex] || titles[0];\n\n        if (!HAS_GSAP) {\n            titleEl.textContent = data.title;\n            subtitleEl.textContent = data.subtitle;\n            return;\n        }\n\n        // Animate title change\n        gsap.to([titleEl, subtitleEl], {\n            opacity: 0,\n            y: -10,\n            duration: 0.3,\n            onComplete: () => {\n                titleEl.textContent = data.title;\n                subtitleEl.textContent = data.subtitle;\n\n                gsap.to([titleEl, subtitleEl], {\n                    opacity: 1,\n                    y: 0,\n                    duration: 0.4,\n                    stagger: 0.1\n                });\n            }\n        });\n    }\n"""

text, count = pattern_title.subn(replacement_title, text)
if count != 1:
    raise SystemExit('updateTitleCard pattern not replaced')

path.write_text(text)
